pipelines:
  branches: # Automated triggers on commits to branches
    master: # -- When committing to master branch
    - step:
        deployment: production
        caches:
          - composer
        script:
          - git ftp push --user rishabh@amourint.com --passwd R1shabh@123 ftp://77.104.185.154