# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2.1

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp init --user erp_amour@erp.amourint.com --passwd mcn]_CTBS9nS ftp://ftp.sololuxury.co.in/sololuxury_app
