name: Laravel-Pint

on:
  push:
    branches: ["master"]

jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    # services:
    #   mysql:
    #     image: mysql:5.7
    #     env:
    #       MYSQL_DATABASE: erp
    #       MYSQL_USER: user
    #       MYSQL_PASSWORD: secret
    #       MYSQL_ROOT_PASSWORD: secretroot
    #     ports:
    #       - 3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Verify MySQL connection
      #   run: |
      #     mysql --version
      #     sudo apt-get install -y mysql-client
      #     mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uuser -psecret -e "SHOW DATABASES"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          COMPOSER_TOKEN: ${{ secrets.CI_TOKEN }}
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      # - name: Prepare the application
      #   run: |
      #     php -r "file_exists('.env') || copy('.env.example', '.env');"
      #     php artisan key:generate
      # - name: Clear Config
      #   run: php artisan config:clear
      - name: "Run laravel pint"
        run: ./vendor/bin/pint
      - name: "Push the changes to Git"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Laravel Pint changes
