name: Laravel-Pint

on:
  push:
    branches: ["master"]

jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Setup PHP
      #   uses: shivammathur/setup-php@v2
      #   env:
      #     COMPOSER_TOKEN: ${{ secrets.CI_SECRET }}
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
      - name: Install composer dependencies
        uses: php-actions/composer@v6
      - name: "Run laravel pint"
        run: ./vendor/bin/pint
      - name: "Push the changes to Git"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Laravel Pint changes
