name: Prettier

on:
  push:
    branches: ["master"]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,css,md}
          only_changed: True
          github_token: ${{ secrets.PERSONAL_TOKEN }}
